version: "3"

services:
  python:
    build:
      context: ./flask-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis

  redis:
    image: "redis:alpine"